// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/chat/actions/send-message': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/actions/send-message.post').default>>>>
    }
    '/api/chat/hooks/relay': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/hooks/relay.post').default>>>>
    }
    '/api/chat/hooks/reply': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/hooks/reply.post').default>>>>
    }
    '/api/chat/update-user': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/update-user.post').default>>>>
    }
    '/api/email/forgot-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/email/forgot-password.post').default>>>>
    }
    '/api/email/new-user-confirmation': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/email/new-user-confirmation.post').default>>>>
    }
    '/api/email/reset-password': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/email/reset-password.post').default>>>>
    }
    '/api/friends/add': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/friends/add.post').default>>>>
    }
    '/api/square/create-card': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/square/create-card.post').default>>>>
    }
    '/api/square/create-checkout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/square/create-checkout.post').default>>>>
    }
    '/api/square/create-customer': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/square/create-customer.post').default>>>>
    }
    '/api/square/list-catalog': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/square/list-catalog.post').default>>>>
    }
    '/api/square/pay-order': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/square/pay-order.post').default>>>>
    }
    '/api/square/payment': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/square/payment.post').default>>>>
    }
    '/api/square/place-order': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/square/place-order.post').default>>>>
    }
    '/api/square/retrieve-item': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/square/retrieve-item.post').default>>>>
    }
    '/api/utils/secure-token': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/utils/secure-token.get').default>>>>
    }
    '/_ws': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/_ws').default>>>>
    }
    '/sse': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/sse').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/.well-known/security.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@zadigetvoltaire/nuxt-well-known/dist/runtime/server/middleware/security-txt').default>>>>
    }
    '/.well-known/change-password': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@zadigetvoltaire/nuxt-well-known/dist/runtime/server/middleware/change-password').default>>>>
    }
    '/.well-known/apple-developer-merchantid-domain-association': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@zadigetvoltaire/nuxt-well-known/dist/runtime/server/middleware/content-uri').default>>>>
    }
    '/.well-known/content-uri.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@zadigetvoltaire/nuxt-well-known/dist/runtime/server/middleware/content-uri').default>>>>
    }
  }
}
export {}