services:
  - type: web
    name: nsight_frontend
    env: node
    plan: starter
    buildCommand: npm cache clean --force && npm install && npm install --save nuxt && npm run build
    startCommand: npm run start
    healthCheckPath: /
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
