// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/13/2025, 12:17:29 PM
const configMerger = require("/Applications/MAMP/htdocs/www/NSIGHT_PROJECT/nsight-frontend/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Applications/MAMP/htdocs/www/NSIGHT_PROJECT/nsight-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/MAMP/htdocs/www/NSIGHT_PROJECT/nsight-frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/MAMP/htdocs/www/NSIGHT_PROJECT/nsight-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/MAMP/htdocs/www/NSIGHT_PROJECT/nsight-frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/MAMP/htdocs/www/NSIGHT_PROJECT/nsight-frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/MAMP/htdocs/www/NSIGHT_PROJECT/nsight-frontend/plugins/**/*.{js,ts,mjs}","/Applications/MAMP/htdocs/www/NSIGHT_PROJECT/nsight-frontend/stores/**/*.{js,ts,mjs}","/Applications/MAMP/htdocs/www/NSIGHT_PROJECT/nsight-frontend/composables/**/*.{js,ts,mjs}","/Applications/MAMP/htdocs/www/NSIGHT_PROJECT/nsight-frontend/utils/**/*.{js,ts,mjs}","/Applications/MAMP/htdocs/www/NSIGHT_PROJECT/nsight-frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Applications/MAMP/htdocs/www/NSIGHT_PROJECT/nsight-frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Applications/MAMP/htdocs/www/NSIGHT_PROJECT/nsight-frontend/app.config.{js,ts,mjs}"] }));

module.exports = config
